# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-16 23:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0045_auto_20170208_2234'),
        ('anagrafica', '0045_auto_20170211_1826'),
        ('anagrafica', '0045_refactor_nome_cognome'),
    ]

    operations = [
    ]
