# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-19 09:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0045_auto_20170219_0916'),
        ('anagrafica', '0046_merge'),
    ]

    operations = [
    ]
